### ISSUE TITLE
Problem running GIMIC on Ubuntu 23.10

### ISSUE THREAD

**Issue by Quark195** [qmcurrents/gimic#308]
Dear GIMIC Developers,

Four months ago, I successfully installed your program on my computer. However, after a recent upgrade of the Ubuntu operating system to version 23.10, an issue with running GIMIC has arisen. When attempting to launch the program, I receive the following error:

`Traceback (most recent call last):
  File "/home/quark/gimic/build/bin/gimic", line 21, in <module>
    from fgimic import getkw
  File "/home/quark/gimic/build/lib/python/site-packages/gimic/fgimic/getkw.py", line 20, in <module>
    from pyparsing import \
ImportError: cannot import name 'commaSeparatedList' from 'pyparsing' (/home/quark/anaconda3/lib/python3.10/site-packages/pyparsing/__init__.py)`

I would greatly appreciate it if you could assist me in resolving this issue. I am willing to provide any additional information that may be required to troubleshoot and fix this error.

Thank you in advance for your help!

**Comment by Quark195** [comment]
I also cannot reinstall because the following error occurs:
`(gimic) gimic_new/build$ make
[  2%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/kinds.f90.o
[  4%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/settings.f90.o
[  7%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/teletype.f90.o
[  9%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/globals.f90.o
[ 11%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/tensor.f90.o
[ 14%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/acid.f90.o
[ 16%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gtodefs.f90.o
[ 19%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/intgrl.f90.o
[ 21%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/basis.f90.o
[ 23%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/factorial.f90.o
[ 26%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/cao2sao.f90.o
[ 28%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/caos.f90.o
[ 30%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/bfeval.f90.o
[ 33%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/reorder.f90.o
[ 35%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/dens.f90.o
/media/quark/M2/gimic_new/src/libgimic/dens.f90(322): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
            read(XDFD, '(4d20.14)') mos(1:4,i)
---------------------------^
[ 38%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gaussint.f90.o
[ 40%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gausspoints.f90.o
[ 42%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/jtensor.F90.o
[ 45%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/timer.f90.o
[ 47%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/gimic_interface.f90.o
[ 50%] Building Fortran object src/libgimic/CMakeFiles/gimic2.dir/lip.f90.o
[ 52%] Building C object src/libgimic/CMakeFiles/gimic2.dir/gausspoints.c.o
[ 54%] Building CXX object src/libgimic/CMakeFiles/gimic2.dir/GimicInterface.cpp.o
icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
In file included from /usr/include/c++/13/cwchar(44),
                 from /usr/include/c++/13/bits/postypes.h(40),
                 from /usr/include/c++/13/iosfwd(42),
                 from /usr/include/c++/13/ios(40),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/wchar.h(422): error: identifier "_Float32" is undefined
  extern _Float32 wcstof32 (const wchar_t *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cwchar(44),
                 from /usr/include/c++/13/bits/postypes.h(40),
                 from /usr/include/c++/13/iosfwd(42),
                 from /usr/include/c++/13/ios(40),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/wchar.h(427): error: identifier "_Float64" is undefined
  extern _Float64 wcstof64 (const wchar_t *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cwchar(44),
                 from /usr/include/c++/13/bits/postypes.h(40),
                 from /usr/include/c++/13/iosfwd(42),
                 from /usr/include/c++/13/ios(40),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/wchar.h(432): error: identifier "_Float128" is undefined
  extern _Float128 wcstof128 (const wchar_t *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cwchar(44),
                 from /usr/include/c++/13/bits/postypes.h(40),
                 from /usr/include/c++/13/iosfwd(42),
                 from /usr/include/c++/13/ios(40),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/wchar.h(437): error: identifier "_Float32x" is undefined
  extern _Float32x wcstof32x (const wchar_t *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cwchar(44),
                 from /usr/include/c++/13/bits/postypes.h(40),
                 from /usr/include/c++/13/iosfwd(42),
                 from /usr/include/c++/13/ios(40),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/wchar.h(442): error: identifier "_Float64x" is undefined
  extern _Float64x wcstof64x (const wchar_t *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cwchar(44),
                 from /usr/include/c++/13/bits/postypes.h(40),
                 from /usr/include/c++/13/iosfwd(42),
                 from /usr/include/c++/13/ios(40),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/wchar.h(649): error: identifier "_Float32" is undefined
  extern _Float32 wcstof32_l (const wchar_t *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cwchar(44),
                 from /usr/include/c++/13/bits/postypes.h(40),
                 from /usr/include/c++/13/iosfwd(42),
                 from /usr/include/c++/13/ios(40),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/wchar.h(655): error: identifier "_Float64" is undefined
  extern _Float64 wcstof64_l (const wchar_t *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cwchar(44),
                 from /usr/include/c++/13/bits/postypes.h(40),
                 from /usr/include/c++/13/iosfwd(42),
                 from /usr/include/c++/13/ios(40),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/wchar.h(661): error: identifier "_Float128" is undefined
  extern _Float128 wcstof128_l (const wchar_t *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cwchar(44),
                 from /usr/include/c++/13/bits/postypes.h(40),
                 from /usr/include/c++/13/iosfwd(42),
                 from /usr/include/c++/13/ios(40),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/wchar.h(667): error: identifier "_Float32x" is undefined
  extern _Float32x wcstof32x_l (const wchar_t *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cwchar(44),
                 from /usr/include/c++/13/bits/postypes.h(40),
                 from /usr/include/c++/13/iosfwd(42),
                 from /usr/include/c++/13/ios(40),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/wchar.h(673): error: identifier "_Float64x" is undefined
  extern _Float64x wcstof64x_l (const wchar_t *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/bits/move.h(37),
                 from /usr/include/c++/13/bits/exception_ptr.h(41),
                 from /usr/include/c++/13/exception(164),
                 from /usr/include/c++/13/ios(41),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/c++/13/type_traits(3363): error: type name is not allowed
    inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
                                                              ^

In file included from /usr/include/c++/13/bits/move.h(37),
                 from /usr/include/c++/13/bits/exception_ptr.h(41),
                 from /usr/include/c++/13/exception(164),
                 from /usr/include/c++/13/ios(41),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/c++/13/type_traits(3363): error: type name is not allowed
    inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
                                                                     ^

In file included from /usr/include/c++/13/bits/move.h(37),
                 from /usr/include/c++/13/bits/exception_ptr.h(41),
                 from /usr/include/c++/13/exception(164),
                 from /usr/include/c++/13/ios(41),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/c++/13/type_traits(3363): error: identifier "__is_convertible" is undefined
    inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
                                             ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(141): error: identifier "_Float32" is undefined
  extern _Float32 strtof32 (const char *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(147): error: identifier "_Float64" is undefined
  extern _Float64 strtof64 (const char *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(153): error: identifier "_Float128" is undefined
  extern _Float128 strtof128 (const char *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(159): error: identifier "_Float32x" is undefined
  extern _Float32x strtof32x (const char *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(165): error: identifier "_Float64x" is undefined
  extern _Float64x strtof64x (const char *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(299): error: identifier "_Float32" is undefined
                       _Float32 __f)
                       ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(305): error: identifier "_Float64" is undefined
                       _Float64 __f)
                       ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(311): error: identifier "_Float128" is undefined
                        _Float128 __f)
                        ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(317): error: identifier "_Float32x" is undefined
                        _Float32x __f)
                        ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(323): error: identifier "_Float64x" is undefined
                        _Float64x __f)
                        ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(436): error: identifier "_Float32" is undefined
  extern _Float32 strtof32_l (const char *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(443): error: identifier "_Float64" is undefined
  extern _Float64 strtof64_l (const char *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(450): error: identifier "_Float128" is undefined
  extern _Float128 strtof128_l (const char *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(457): error: identifier "_Float32x" is undefined
  extern _Float32x strtof32x_l (const char *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cstdlib(79),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/stdlib.h(464): error: identifier "_Float64x" is undefined
  extern _Float64x strtof64x_l (const char *__restrict __nptr,
         ^

In file included from /usr/include/c++/13/cstdlib(81),
                 from /usr/include/c++/13/ext/string_conversions.h(43),
                 from /usr/include/c++/13/bits/basic_string.h(4097),
                 from /usr/include/c++/13/string(54),
                 from /usr/include/c++/13/bits/locale_classes.h(40),
                 from /usr/include/c++/13/bits/ios_base.h(41),
                 from /usr/include/c++/13/ios(44),
                 from /usr/include/c++/13/ostream(40),
                 from /usr/include/c++/13/iostream(41),
                 from /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp(1):
/usr/include/c++/13/bits/std_abs.h(142): error: identifier "__builtin_fabsf128" is undefined
      return __builtin_fabsf128(__x);
             ^

compilation aborted for /media/quark/M2/gimic_new/src/libgimic/GimicInterface.cpp (code 2)
make[2]: *** [src/libgimic/CMakeFiles/gimic2.dir/build.make:328: src/libgimic/CMakeFiles/gimic2.dir/GimicInterface.cpp.o] Error 2
make[1]: *** [CMakeFiles/Makefile2:189: src/libgimic/CMakeFiles/gimic2.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
`

**Comment by gibbs8** [comment]
I had the same error. I had to edit the _getkw.py_ file. The problem was solved by removing "commaSeparatedList," and "downcaseTokens," from lines 25 and 26, respectively.

**Comment by Quark195** [comment]
Thank you very much, it's working again!
